### ISSUE TITLE
Support for AWS SQS

### ISSUE THREAD

**Issue by johntdyer** [danmia/pcapdaemon#1]
I would love to be able to support running this in multiple networks and link up to a single SQS queue for triggering captures.

**Comment by danmia** [comment]
Amazon SQS support added.  Let me know if you find any bugs.  Configuration options are as follows:

[sqs]
listen         = true
region        = "us-east-1"
accessid = "xxxxxxxxxxxxxxxxxxxxxx"
accesskey = "xxxxxxxxxxxxxxxxxxxxxxx"
url = "https://sqs.us-east-1.amazonaws.com/234234234/yourqueue"
waitseconds = 20  //long poll time, I wouldn't change this
chunksize = 10  // number of messages to process concurrently
