### ISSUE TITLE
Support uploads to S3

### ISSUE THREAD

**Issue by johntdyer** [danmia/pcapdaemon#2]
It would be nice if that the end of a capture the daemon could upload to a configureable storage service, such as AWS S3.

**Comment by danmia** [comment]
I'm not an AWS user so I'd prefer not to make a bunch of assumptions.

Questions like:
What needs to be globally configurable?
What needs to be added to the JSON message so it can bet set per capture?
What constraints or protections are needed to protect the user?
Are there size limits etc and how should they be imposed?

**Comment by danmia** [comment]
Does this make sense?

{
    "node": "any",
    "interface": ["enp0s25"],
    "tags": "blah,tagme,stuff",
    "bpf": "port 22",
    "customer": "importantcustomer",
    "snap": 1500,
    "packets": 25,
    "alertid": 655443,
    "timeout": 15,
    "folder": "myfolder",
    "bucket": "mybucket",
    "acl": "public-read",
    "region": "us-east-1"
}

**Comment by danmia** [comment]
Done.  Readme updated

**Comment by johntdyer** [comment]
You sir are a gentleman and a scholar!!

**Comment by danmia** [comment]
Tons of options I don't understand but hopefully I hit the high points.
Give me some time on the other one.  It's a bit more foreign but I'll take
a look and see.
