### ISSUE TITLE
Build failing for OS Linux

### ISSUE THREAD

**Issue by krsboone** [danmia/pcapdaemon#9]
When attempting to build for Linux (OS = Linux, ARCH = amd64) I'm encountering a few failures that prevent the build from succeeding:

```
../src/github.com/danmia/pcapdaemon/capture.go:27:16: undefined: pcap.Handle
../src/github.com/danmia/pcapdaemon/capture.go:144:16: undefined: pcap.OpenLive
../src/github.com/danmia/pcapdaemon/main.go:30:24: undefined: pcap.Interface
../src/github.com/danmia/pcapdaemon/main.go:43:13: undefined: pcap.FindAllDevs
```

Details of my local environment:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/krboone/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rr/82814jx93g569tqlk0f8g7k40000gn/T/go-build246226278=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

The build has been attempted from a few different machines, using native GO & various other cross-compile tools.

Am I possibly "doing it wrong", or could something have recently changed in the sourced libs?

Thanks for your assistance!

-Kris

**Comment by danmia** [comment]
did you do a "go get" in the pcapdaemon source directory?  It looks like you don't have the gopacket library.

**Comment by danmia** [comment]
Also worth noting in case these are fresh systems... Make sure you have libpcap-dev (on debian/ubuntu based systems) or libpcap-devel (RHEL/CentOS based systems.  You don't need it to build but you'll need it to run.

**Comment by krsboone** [comment]
Thank you very much for such rapid response! 

Yes, I've done the "go get". Correct, the "gopacket" library was not previously on my system; I've now installed it manually, but still hitting the same stumbling point.

Thank you for the additional notes; that will surely save me some time!

**Comment by danmia** [comment]
Sounds like your GOPATH isn't set properly if it can't find the library.  You say you're building on linux? That ENV you put in the ticket looks like mac to me.  OS is Darwin ... home directory in /Users etc.

Also ... Where is the pcapdaemon src? and where is the gopacket src relative to one another?

**Comment by krsboone** [comment]
Correct, building on local Mac for "linux/amd64". Attempted building using "gox" cross-compiler & native "go" functionality.

The pcapdaemon src:
/Users/krboone/go/src/github.com/danmia/pcapdaemon

The gopacket src:
/Users/krboone/go/src/github.com/google/gopacket

**Comment by danmia** [comment]
That exact setup builds for me on both my macs.  I'm not using (nor have I ever used) gccgo.  I'd remove all that stuff from your environment and just build with the standard go command with a "go install" and see if you get the same result.

**Comment by krsboone** [comment]
From your macs, are you able to build for linux?

Building for mac is successful, no issues there; "go install" is successful without adjusting any env vars.

**Comment by danmia** [comment]
Ok .. sorry for the misunderstanding.  I build for other OSs in VMs so I haven't done much cross compiling.  It looks like this is a function of the architecture dependent pcap libraries that gopacket relies on.  You'll probably have to link in an architecture specific pcap.h/libpcap.  The gopacket folks could probably give some better guidance on the topic.

**Comment by krsboone** [comment]
No worries whatsoever; I'm very grateful for your assistance.

Makes sense, I'll give that a shot.

Closing this out as it's not an issue with the pcapdaemon.

**Comment by krsboone** [comment]
Just wanted to follow up and confirm that I'm good to go this morning. Thanks again for the assistance.

**Comment by danmia** [comment]
np! Glad to hear it.  What did your final solution end up being?  Maybe something I should add to the readme?

**Comment by krsboone** [comment]
Still working on a solution for cross-compiling; will certainly share details if / when I make some progress there. Ended up just building from Linux host to get everything going.

I must say, this is an impressive tool! Thank you for sharing it.
